# Site settings
title: 每天多一点
email: dq0572255@126.com
description: 

baseurl: "/dailycomments/" # the subpath of your site, e.g. /blog/
url: "http://gitcommit.dailycomments"
# twitter_username: jekyllrb
github_username:  ceciet

# Build settings
markdown: kramdown
extensions: [fenced_code_blocks]

# paging settings
paginate: 10

gems :
  - jekyll-paginate
